language: python

python:
  - '2.7'
  - '3.8'

os:
  - linux

env:
  global:
    - secure: "cROjH+H5bRseY2fgb+GrEvtbE7FlFcTY3nPQ4Bh+HEc8D1TgJk/Y2wO0Z53aImewoe4bgI1J44tdguWqv1CeLvOVPLVuNTOAMIXq0iD6jpR8x/a06nGfY5cbS41EaxIDTL0biNfh1C7KqXirXIEfIddwt7+A2vXP4Vju0MzrCJ77uFuv5QRgtRnjCVV9mkja9Bh5wQl8BpXyTTvkEcq1MjGoQNrkD7Hl+H6pOmPhWU2SeHednH54f/u81mQYAtb+p8QRQCQdMoKoLAWL1WgH696afhopzFAkduI3yskpRuZrNOJRpUPJZNYYVi/rSlajmksLZpa6vJ2AmAaAfeWxyp4jV8Uz1lnqa7NjCZtXOryhN8vjuKiAgszB4JiLGI3Q2y7KXSsLMCOX3ApQLcWNEkPVUt7r6VNDMBAEWa3Pb8je26nf9n7DvpNIr3YSbREvjtRaRq+K9KJdSMEwvb3TwcTIyNFhd0qHybr0L9h5ndU7hipRhwe0D+U2UWL0aHeWvosIYjhdj4jcfeoHw5Fh1kZFzFn/liSGeALdhWBGu68ighjW8Bsj+Ji2fTeetDOXLFIDh1tlD68E35RMAHOojz623Q2IfbKdIfFQ0V4TCor/qmr6bRHndpWGo5nk9pW4Vvk2u0av1MvR5GFHZUugLOY0HjUFlTU3BYervxBB7e4="
  matrix:
    - OUTLOOK_AUTH=PLAIN GMAIL_AUTH=XOAUTH2
    - OUTLOOK_AUTH=LOGIN GMAIL_AUTH=XOAUTH2

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=2.7.14 OUTLOOK_AUTH=PLAIN GMAIL_AUTH=XOAUTH2
    - os: osx
      language: generic
      env: PYTHON=2.7.14 OUTLOOK_AUTH=LOGIN GMAIL_AUTH=XOAUTH2
  allow_failures:
    - os: osx

cache: pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install openssl readline;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OSX_BREW_SSLCACERTFILE="/usr/local/etc/openssl/cert.pem";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated pyenv || brew upgrade pyenv;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $PYTHON; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PYENV_VERSION="${PYTHON}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/Users/travis/.pyenv/shims:${PATH}";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv virtualenv $PYTHON myvenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv versions; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m pip install -U pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python -m easy_install -U setuptools;
    fi

install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - export PATH=$PATH:.
  - python tests/create_conf_file.py

script:
  - "./offlineimap.py -c ./oli-travis.conf"
  - codecov
